--[[--------------------------------------------------------------------
	GoFish
	Click-cast fishing and enhanced fishing sounds.
	Copyright (c) 2013-2016 Phanx <addons@phanx.net>. All rights reserved.
	http://www.wowinterface.com/downloads/info22270-GoFish.html
	http://www.curse.com/addons/wow/gofish
	https://github.com/Phanx/GoFish
----------------------------------------------------------------------]]
local F, _, ns = {}, ...
ns.F = F
------------------------------------------------------------------------
-- English
------------------------------------------------------------------------
F["Black Barracuda School"] = true
F["Cursed Queenfish School"] = true
F["Fever of Stormrays"] = true
F["Highmountain Salmon School"] = true
F["Mossgill Perch School"] = true
F["Runescale Koi School"] = true
F["Abyssal Gulper School"] = true
F["Albino Cavefish School"] = true
F["Blackbelly Mudfish School"] = true
F["Blackwater Whiptail School"] = true
F["Blind Lake Sturgeon School"] = true
F["Bloodsail Wreckage"] = true
F["Bluefish School"] = true
F["Borean Man O' War School"] = true
F["Brackish Mixed School"] = true
F["Brew Frenzied Emperor Salmon"] = true
F["Crane Yolk Pool"] = true
F["Crowded Redbelly Mandarin"] = true
F["Deep Sea Monsterbelly School"] = true
F["Deepsea Sagefish School"] = true
F["Dragonfin Angelfish School"] = true
F["Emperor Salmon School"] = true
F["Fangtooth Herring School"] = true
F["Fat Sleeper School"] = true
F["Fathom Eel Swarm"] = true
F["Felmouth Frenzy School"] = true
F["Feltail School"] = true
F["Fire Ammonite School"] = true
F["Firefin Snapper School"] = true
F["Floating Debris"] = true
F["Floating Wreckage"] = true
F["Giant Mantis Shrimp Swarm"] = true
F["Glacial Salmon School"] = true
F["Glassfin Minnow School"] = true
F["Glimmering Jewel Danio Pool"] = true
F["Glowing Jade Lungfish"] = true
F["Greater Sagefish School"] = true
F["Highland Guppy School"] = true
F["Highland Mixed School"] = true
F["Imperial Manta Ray School"] = true
F["Jade Lungfish School"] = true
F["Jawless Skulker School"] = true
F["Jewel Danio School"] = true
F["Krasarang Paddlefish School"] = true
F["Lagoon Pool"] = true
F["Large Pool of Brew Frenzied Emperor Salmon"] = true
F["Large Pool of Crowded Redbelly Mandarin"] = true
F["Large Pool of Glimmering Jewel Danio"] = true
F["Large Pool of Glowing Jade Lungfish"] = true
F["Large Pool of Sha-Touched Spinefish"] = true
F["Large Pool of Tiger Gourami Slush"] = true
F["Large Swarm of Migrated Reef Octopus"] = true
F["Large Swarm of Panicked Paddlefish"] = true
F["Large Tangled Mantis Shrimp Cluster"] = true
F["Mixed Ocean School"] = true
F["Moonglow Cuttlefish School"] = true
F["Mountain Trout School"] = true
F["Mudfish School"] = true
F["Musselback Sculpin School"] = true
F["Nettlefish School"] = true
F["Oily Abyssal Gulper School"] = true
F["Oily Blackmouth School"] = true
F["Oily Sea Scorpion School"] = true
F["Pool of Blood"] = true
F["Pool of Fire"] = true
F["Pure Water"] = true
F["Redbelly Mandarin School"] = true
F["Reef Octopus Swarm"] = true
F["Sagefish School"] = true
F["Savage Piranha Pool"] = true
F["School of Darter"] = true
F["School of Deviate Fish"] = true
F["Schooner Wreckage"] = true
F["Sea Scorpion School"] = true
F["Sha-Touched Spinefish"] = true
F["Shipwreck Debris"] = true
F["Sparkling Pool"] = true
F["Spinefish School"] = true
F["Sporefish School"] = true
F["Steam Pump Flotsam"] = true
F["Stonescale Eel Swarm"] = true
F["Strange Pool"] = true
F["Swarm of Migrated Reef Octopus"] = true
F["Swarm of Panicked Paddlefish"] = true
F["Tangled Mantid Shrimp Cluster"] = true
F["Tiger Gourami School"] = true
F["Tiger Gourami Slush"] = true
F["Waterlogged Wreckage"] = true
------------------------------------------------------------------------
-- deDE: German
------------------------------------------------------------------------
-- F["Cursed Queenfish School"] = true
-- F["Fever of Stormrays"] = true
F["Blut im Wasser"] = true
F["Blutsegelwrackteile"] = true
F["Brauverrückter Kaiserlachs"] = true
F["Ein Brackwasserschwarm"] = true
F["Ein großer Schwarm glitzernder Juwelendanios"] = true
F["Ein großer Schwarm Sha-berührter Stachelfische"] = true
F["Ein großer Schwarm wimmelnder Rotbauchmandarine"] = true
F["Ein Hochlandschwarm"] = true
F["Ein Schwarm Albinohöhlenfische"] = true
F["Ein Schwarm Bergforellen"] = true
F["Ein Schwarm Blauflossen"] = true
F["Ein Schwarm blinder Seestöre"] = true
F["Ein Schwarm boreanischer Galeeren"] = true
F["Ein Schwarm Dämonenschlundfrenzys"] = true
F["Ein Schwarm Dämonenschlundfrenzys"] = true
F["Ein Schwarm Deviatfische"] = true
F["Ein Schwarm dicker Schläfer"] = true
F["Ein Schwarm Engelsdrachenfische"] = true
F["Ein Schwarm Fangzahnheringe"] = true
F["Ein Schwarm Feuerammoniten"] = true
F["Ein Schwarm Feuerflossenschnapper"] = true
F["Ein Schwarm gewanderter Riffkraken"] = true
F["Ein Schwarm Glasflossenelritzen"] = true
F["Ein Schwarm glitzernder Juwelendanios"] = true
F["Ein Schwarm großer Weisenfische"] = true
F["Ein Schwarm Hochberglachse"] = true
F["Ein Schwarm Hochlandguppys"] = true
F["Ein Schwarm imperialer Mantarochen"] = true
F["Ein Schwarm Jadelungenfische"] = true
F["Ein Schwarm Juwelendanios"] = true
F["Ein Schwarm Kaiserlachse"] = true
F["Ein Schwarm kieferloser Schleicher"] = true
F["Ein Schwarm Krasaranglöffelstöre"] = true
F["Ein Schwarm Matschflosser"] = true
F["Ein Schwarm Meeresfische"] = true
F["Ein Schwarm Mondlichtsepia"] = true
F["Ein Schwarm Mooskiemenbarsche"] = true
F["Ein Schwarm mordlustiger Piranhas"] = true
F["Ein Schwarm Muschelrückengroppen"] = true
F["Ein Schwarm Nesselfische"] = true
F["Ein Schwarm öliger Schwarzmaulfische"] = true
F["Ein Schwarm öliger Seeskorpione"] = true
F["Ein Schwarm ölige Tiefseeschluckaale"] = true
F["Ein Schwarm panischer Krasaranglöffelstöre"] = true
F["Ein Schwarm riesiger Mantisgarnelen"] = true
F["Ein Schwarm Riffkraken"] = true
F["Ein Schwarm Rotbauchmandarine"] = true
F["Ein Schwarm Runenschuppenkoi"] = true
F["Ein Schwarm Schwarzbauchmatschflosser"] = true
F["Ein Schwarm schwarzer Barrakudas"] = true
F["Ein Schwarm Schwarzwasserpeitschflossen"] = true
F["Ein Schwarm Seeskorpione"] = true
F["Ein Schwarm Sha-berührter Stachelfische"] = true
F["Ein Schwarm Sporenfische"] = true
F["Ein Schwarm Stachelfische"] = true
F["Ein Schwarm Stachelflosser"] = true
F["Ein Schwarm Tiefenschluckaale"] = true
F["Ein Schwarm Tiefseemonsterbäuche"] = true
F["Ein Schwarm Tiefseeweisenfische"] = true
F["Ein Schwarm Tigerguramis"] = true
F["Ein Schwarm Weisenfische"] = true
F["Ein Schwarm wimmelnder Rotbauchmandarine"] = true
F["Ein Schwarm Winterlachse"] = true
F["Feuerteich"] = true
F["Glitzernder Teich"] = true
F["Großer Schwarm brauverrückter Kaiserlachse"] = true
F["Großer Schwarm gewanderter Riffkraken"] = true
F["Großer Schwarm leuchtender Jadelungenfische"] = true
F["Großer Schwarm panischer Krasaranglöffelstöre"] = true
F["Großer Schwarm Tigerguramischlick"] = true
F["Großer verhedderter Schwarm riesiger Mantisgarnelen"] = true
F["Klafteraalschwarm"] = true
F["Kranichdotterlache"] = true
F["Lagunenteich"] = true
F["Leuchtender Jadelungenfisch"] = true
F["Reines Wasser"] = true
F["Schiffswrackteile"] = true
F["Schiffswracktrümmer"] = true
F["Schiffswracktrümmer"] = true
F["Schiffswracktrümmer"] = true
F["Schiffswracktrümmer"] = true
F["Schwimmende Trümmer"] = true
F["Schwimmende Wrackteile"] = true
F["Seltsamer Teich"] = true
F["Steinschuppenaalschwarm"] = true
F["Tigerguramischlick"] = true
F["Treibende Wrackteile"] = true
F["Treibgut der Dampfpumpe"] = true
F["Verhedderter Schwarm riesiger Mantisgarnelen"] = true
------------------------------------------------------------------------
-- esES: Spanish
-- esMX: Latin American Spanish
------------------------------------------------------------------------
-- F["Black Barracuda School"] = true
-- F["Cursed Queenfish School"] = true
-- F["Fever of Stormrays"] = true
-- F["Highmountain Salmon School"] = true
-- F["Mossgill Perch School"] = true
-- F["Runescale Koi School"] = true
F["Agua pura"] = true
F["Aguanieve de guramis tigre"] = true
F["Banco de amonites de fuego"] = true
F["Banco de anguilas de las profundidades"] = true
F["Banco de anguilas devoradoras abisales grasas"] = true
F["Banco de anguilas devoradoras abisales"] = true
F["Banco de anguilas escama pétrea"] = true
F["Banco de arenques colmillo"] = true
F["Banco de bagres de Aguasnegras"] = true
F["Banco de bocanegras grasos"] = true
F["Banco de carabelas boreales"] = true
F["Banco de cavernosos albinos"] = true
F["Banco de cotos gordos"] = true
F["Banco de danios enjoyados"] = true
F["Banco de dardos"] = true
F["Banco de escorpinas grasas"] = true
F["Banco de escorpinas"] = true
F["Banco de esturiones ciegos de lago"] = true
F["Banco de frenesís bocaviles"] = true
F["Banco de guramis tigre"] = true
F["Banco de lebistes de las Tierras Altas"] = true
F["Banco de mandarines panzarroja"] = true
F["Banco de mantas raya imperiales"] = true
F["Banco de medusas"] = true
F["Banco de mezcla oceánica"] = true
F["Banco de pargos de fuego"] = true
F["Banco de peces alveolares de jade"] = true
F["Banco de peces ángel aletadragón"] = true
F["Banco de peces descarriados"] = true
F["Banco de peces escorpión mejillón"] = true
F["Banco de peces espinosos"] = true
F["Banco de peces sabiola marfunda"] = true
F["Banco de pecesporas"] = true
F["Banco de pezazules"] = true
F["Banco de pezfangos panzanegra"] = true
F["Banco de pezfangos"] = true
F["Banco de pezqueñines Aleta de Nácar"] = true
F["Banco de pirañas salvajes"] = true
F["Banco de poliodóntidos de Krasarang"] = true
F["Banco de pulpos de arrecife emigrados"] = true
F["Banco de pulpos de arrecife"] = true
F["Banco de sabiolas superior"] = true
F["Banco de sabiolas"] = true
F["Banco de salmones emperador"] = true
F["Banco de salmones glaciales"] = true
F["Banco de sepias resplandor lunar"] = true
F["Banco de tripayuyus de las profundidades"] = true
F["Banco de truchas de montaña"] = true
F["Banco de vagadores mermaquija"] = true
F["Banco grande de pulpos de arrecife emigrados"] = true
F["Banco mixto de las Tierras Altas"] = true
F["Banco mixto salobre"] = true
F["Charca grande de aguanieve de guramis tigre"] = true
F["Charca grande de danios enjoyados centelleantes"] = true
F["Charca grande de mandarines panzarroja atiborrados"] = true
F["Charca grande de peces alveolares de jade resplandecientes"] = true
F["Charca grande de peces espinosos influenciados por el sha"] = true
F["Charca grande de salmones emperador demenciados por la cerveza"] = true
F["Charco de laguna"] = true
F["Charco de sangre"] = true
F["Charco de yema de grulla"] = true
F["Enjambre de gambas mantis enredadas"] = true
F["Enjambre de gambas mantis gigantes"] = true
F["Enjambre de poliodóntidos aterrados"] = true
F["Enjambre grande de gambas mantis enredadas"] = true
F["Enjambre grande de poliodóntidos aterrados"] = true
F["Estanque de danios enjoyados centelleantes"] = true
F["Mandarines panzarroja atiborrados"] = true
F["Pez alveolar de jade resplandeciente"] = true
F["Pez espinoso influenciado por el sha"] = true
F["Piscina de fuego"] = true
F["Piscinia extraño"] = true
F["Poza brillante"] = true
F["Restos de goleta"] = true
F["Restos de los Velasangre"] = true
F["Restos de naufragio"] = true
F["Restos de un naufragio"] = true
F["Restos de naufragio"] = true
F["Restos encharcados"] = true
F["Restos flotando"] = true
F["Restos flotantes de bomba de vapor"] = true
F["Salmón emperador demenciado por la cerveza"] = true
------------------------------------------------------------------------
-- frFR: French
------------------------------------------------------------------------
-- F["Black Barracuda School"] = true
-- F["Cursed Queenfish School"] = true
-- F["Fever of Stormrays"] = true
-- F["Highmountain Salmon School"] = true
-- F["Mossgill Perch School"] = true
-- F["Runescale Koi School"] = true
F["Amas de crevettes-mantes enchevêtrées"] = true
F["Banc d’ammonites de feu"] = true
F["Banc d’esturgeons jaunes aveugles"] = true
F["Banc d'anguilles des profondeurs"] = true
F["Banc d'anguilles pierre-écaille"] = true
F["Banc de baudroies abyssales"] = true
F["Banc de bouches-noires huileux"] = true
F["Banc de crevettes-mantes géantes"] = true
F["Banc de danios joyaux scintillants"] = true
F["Banc de danios joyaux"] = true
F["Banc de dards"] = true
F["Banc de demoiselles aileron-de-dragon"] = true
F["Banc de dipneustes de jade"] = true
F["Banc de dormeurs tachetés"] = true
F["Banc de furtifs agnathes"] = true
F["Banc de gangregoulots frénétiques"] = true
F["Banc de gouramis tigres"] = true
F["Banc de grandes sagerelles"] = true
F["Banc de grangousiers des abysses huileux"] = true
F["Banc de grangousiers des abysses"] = true
F["Banc de guppys des Hautes-terres"] = true
F["Banc de harengs crocs-pointus"] = true
F["Banc de hokis des flots noirs"] = true
F["Banc de lutjans de nagefeu"] = true
F["Banc de mandarins ventre-rouge"] = true
F["Banc de méduses"] = true
F["Banc de poissons déviants"] = true
F["Banc de poissons océaniques"] = true
F["Banc de poissons-hérissons"] = true
F["Banc de poissons-méduses boréens"] = true
F["Banc de poissons-spatules de Krasarang"] = true
F["Banc de poissons-spores"] = true
F["Banc de poulpes des récifs"] = true
F["Banc de raies manta impériales"] = true
F["Banc de rascasses dos-de-moule"] = true
F["Banc de sagerelles abyssales"] = true
F["Banc de sagerelles"] = true
F["Banc de saumons empereurs"] = true
F["Banc de saumons glaciaires"] = true
F["Banc de scorpions de mer huileux"] = true
F["Banc de scorpions de mer"] = true
F["Banc de seiches lueur-de-lune"] = true
F["Banc de tassergals"] = true
F["Banc de tétras cavernicoles albinos"] = true
F["Banc de truites de montagne"] = true
F["Banc de vairons nageverres"] = true
F["Banc d'éperlans ventre-noir"] = true
F["Banc d'éperlans"] = true
F["Banc mixte des Hautes-terres"] = true
F["Banc mixte en eaux saumâtres"] = true
F["Bassin de piranhas sauvages"] = true
F["Bassin du lagon"] = true
F["Bassin étincelant"] = true
F["Bassin étrange"] = true
F["Boue de gouramis tigres"] = true
F["Colonie de poissons-spatules paniqués"] = true
F["Colonie de poulpes des récifs migrants"] = true
F["Débris d’épave"] = true
F["Débris de goélette"] = true
F["Débris de la Voile sanglante"] = true
F["Débris d'épave"] = true
F["Débris flottants"] = true
F["Débris trempés"] = true
F["Déchets flottants"] = true
F["Détritus de la pompe à vapeur"] = true
F["Dipneuste de jade luminescent"] = true
F["Eau pure"] = true
F["Flaque de feu"] = true
F["Flaque de jaune d’œuf de grue"] = true
F["Flaque de sang"] = true
F["Grand amas de crevettes-mantes enchevêtrées"] = true
F["Grande colonie de poissons-spatules paniqués"] = true
F["Grande colonie de poulpes des récifs migrants"] = true
F["Grande réserve de boue de gouramis tigres"] = true
F["Grande réserve de danios joyaux scintillants"] = true
F["Grande réserve de dipneustes de jade luminescents"] = true
F["Grande réserve de mandarins ventre-rouge agglutinés"] = true
F["Grande réserve de poissons-hérissons touchés par les sha"] = true
F["Grande réserve de saumons empereurs affolés par la bière"] = true
F["Mandarins ventre-rouge agglutinés"] = true
F["Poisson-hérisson touché par les sha"] = true
F["Saumon empereur affolé par la bière"] = true
------------------------------------------------------------------------
-- itIT: Italian
------------------------------------------------------------------------
-- F["Black Barracuda School"] = true
-- F["Cursed Queenfish School"] = true
-- F["Fever of Stormrays"] = true
-- F["Highmountain Salmon School"] = true
-- F["Mossgill Perch School"] = true
-- F["Runescale Koi School"] = true
-- F["Strange Pool"] = true
F["Acqua Pura"] = true
F["Banco Affollato di Panciarossa Orientali"] = true
F["Banco di Ammoniti del Fuoco"] = true
F["Banco di Anguille Abissali"] = true
F["Banco di Anguille Abissali delle Profondità"] = true
F["Banco di Anguille Abissali delle Profondità Oleosi"] = true
F["Banco di Anguille Squamapietra"] = true
F["Banco di Aringhe Zannute"] = true
F["Banco di Barracuda Arcobaleno"] = true
F["Banco di Bavose delle Alture"] = true
F["Banco di Boccanera Oleosi"] = true
F["Banco di Danii Luccicanti"] = true
F["Banco di Danii"] = true
F["Banco di Dipnoi di Giada Luminosi"] = true
F["Banco di Dipnoi di Giada"] = true
F["Banco di Dragonetti"] = true
F["Banco di Eleotridi Grassi"] = true
F["Banco di Frustaliane Nere"] = true
F["Banco di Gamberi Mantide Aggrovigliati"] = true
F["Banco di Gamberi Mantide Giganti"] = true
F["Banco di Gran Pescisalvia"] = true
F["Banco di Gurami Tigrati Infangati"] = true
F["Banco di Gurami Tigrati"] = true
F["Banco di Mante Imperiali"] = true
F["Banco di Meduse Boreali"] = true
F["Banco di Panciarossa Mandarini"] = true
F["Banco di Pescecauti Sdentati"] = true
F["Banco di Pesci Angelo Pinnadrago"] = true
F["Banco di Pesci Azzurri"] = true
F["Banco di Pesci Cavernicoli Albini"] = true
F["Banco di Pesci d'Acqua Salmastra"] = true
F["Banco di Pesci delle Alture"] = true
F["Banco di Pesci di Vetro"] = true
F["Banco di Pesci Mutanti"] = true
F["Banco di Pesci Oceanici"] = true
F["Banco di Pesci Palla Oceanici"] = true
F["Banco di Pesci Persico"] = true
F["Banco di Pesci Scorpione Toccati dallo Sha"] = true
F["Banco di Pesci Scorpione"] = true
F["Banco di Pesci Spatola di Krasarang"] = true
F["Banco di Pesci Spatola nel Panico"] = true
F["Banco di Pescifango Ventrenero"] = true
F["Banco di Pescifango"] = true
F["Banco di Pescisalvia Oceanici"] = true
F["Banco di Pescisalvia"] = true
F["Banco di Pescispora"] = true
F["Banco di Polpi di Scogliera Migrati"] = true
F["Banco di Polpi di Scogliera"] = true
F["Banco di Ragnoli"] = true
F["Banco di Salmoni Imperiali Frenetici"] = true
F["Banco di Salmoni Imperiali"] = true
F["Banco di Salmoni Nordici"] = true
F["Banco di Scorpioni di Mare Oleosi"] = true
F["Banco di Scorpioni di Mare"] = true
F["Banco di Seppie di Lunafulgida"] = true
F["Banco di Storioni di Lago Ciechi"] = true
F["Banco di Trote Fario"] = true
F["Banco di Vildenti Frenetici"] = true
F["Grosso Banco Affollato di Panciarossa Orientali"] = true
F["Grosso Banco di Danii Luccicanti"] = true
F["Grosso Banco di Dipnoi di Giada Luminosi"] = true
F["Grosso Banco di Gamberi Mantide Aggrovigliati"] = true
F["Grosso Banco di Gurami Tigrati Infangati"] = true
F["Grosso Banco di Pesci Scorpione Toccati dallo Sha"] = true
F["Grosso Banco di Pesci Spatola nel Panico"] = true
F["Grosso Banco di Polpi di Scogliera Migrati"] = true
F["Grosso Banco di Salmoni Imperiali Frenetici"] = true
F["Pezzi del Relitto"] = true
F["Pozza della Laguna"] = true
F["Pozza di Fuoco"] = true
F["Pozza di Piranha Selvaggi"] = true
F["Pozza di Sangue"] = true
F["Pozza di Tuorlo di Gru"] = true
F["Pozza Luccicante"] = true
F["Pozza Strano"] = true
F["Relitti Galleggianti"] = true
F["Rottami dei Velerosse"] = true
F["Rottami di Goletta"] = true
F["Rottami di Pompa del Vapore"] = true
F["Rottami Fradici"] = true
F["Rottami Galleggianti"] = true
------------------------------------------------------------------------
-- ptBR: Brazilian Portugese
------------------------------------------------------------------------
-- F["Black Barracuda School"] = true
-- F["Cursed Queenfish School"] = true
-- F["Fever of Stormrays"] = true
-- F["Highmountain Salmon School"] = true
-- F["Mossgill Perch School"] = true
-- F["Runescale Koi School"] = true
F["Cardume de Boca-grandes Abissais Oleosos"] = true
F["Cardume de Mandarins Vermelhos"] = true
F["Restos de Naufrágio"] = true
F["Piscina Estranha"] = true
F["Cardume de Polvos do Recife Migrados"] = true
F["Agrupamento de Polvos dos Recifes"] = true
F["Água Pura"] = true
F["Cardume da Lagoa"] = true
F["Cardume de Acarás-bandeira Pinadragos"] = true
F["Cardume de Amonitas de Fogo"] = true
F["Cardume de Arenques Presadentes"] = true
F["Cardume de Arraias-jamanta Imperiais"] = true
F["Cardume de Azorragues Aguanegra"] = true
F["Cardume de Azulinhos"] = true
F["Cardume de Bagres-cegos Albinos"] = true
F["Cardume de Boca-grandes Abissais"] = true
F["Cardume de Bocaneras Oleosos"] = true
F["Cardume de Caravelas Boreanas"] = true
F["Cardume de Escorpiões do Mar Oleosos"] = true
F["Cardume de Escorpiões do Mar"] = true
F["Cardume de Esporosos"] = true
F["Cardume de Esturjões Cegos do Lago"] = true
F["Cardume de Farnesim Bocavil"] = true
F["Cardume de Gouramis-tigre"] = true
F["Cardume de Lebiste das Terras Altas"] = true
F["Cardume de Lulas Brilho-da-lua"] = true
F["Cardume de Mangangás Berbidorsos"] = true
F["Cardume de Manjubinhas Galhavítreas"] = true
F["Cardume de Muçuns"] = true
F["Cardume de Muçuns-de-barriga-preta"] = true
F["Cardume de Pançudos do Mar Profundo"] = true
F["Cardume de Pargos Pinafogos"] = true
F["Cardume de Peixes Anormais"] = true
F["Cardume de Peixes-espátula de Krasarang"] = true
F["Cardume de Peixes-espátula em Pânico"] = true
F["Cardume de Peixes-espinho"] = true
F["Cardume de Peixes-urtiga"] = true
F["Cardume de Peixes-zebra"] = true
F["Cardume de Pestanas Gordos"] = true
F["Cardume de Piramboias de Jade"] = true
F["Cardume de Piranha Selvagem"] = true
F["Cardume de Platis"] = true
F["Cardume de Sabichões Abissais"] = true
F["Cardume de Sabichões Maiores"] = true
F["Cardume de Sabichões"] = true
F["Cardume de Salmões Glaciais"] = true
F["Cardume de Salmões Imperiais"] = true
F["Cardume de Sorrateiros Sem-queixo"] = true
F["Cardume de Truta da Montanha"] = true
F["Cardume Misto das Terras Altas"] = true
F["Cardume Misto do Mar"] = true
F["Cardume Misto Salobre"] = true
F["Destroços da Bomba de Vapor"] = true
F["Destroços da Escuna"] = true
F["Destroços do Naufrágio"] = true
F["Destroços dos Vela Sangrenta"] = true
F["Destroços Encharcados"] = true
F["Destroços Flutuantes"] = true
F["Enxame de Camarões-grilo Gigantes"] = true
F["Grande Cardume de Enguias de Profundeza"] = true
F["Grande Cardume de Enguias Petrescamas"] = true
F["Grande Cardume de Peixes-espátula em Pânico"] = true
F["Grande Cardume de Polvos do Recife Migrados"] = true
F["Grande Monte de Camarões Mantídeos Emaranhados"] = true
F["Grande Poça de Lodo do Gourami-tigre"] = true
F["Grande Poça de Mandarins Vermelhos Amontoados"] = true
F["Grande Poça de Peixes-espinho Tocados pelo Sha"] = true
F["Grande Poça de Piramboias de Jade Brilhantes"] = true
F["Grande Poça de Salmões Imperiais em Frenesi Alcoólico"] = true
F["Grande Tanque de Peixes-zebra Brilhantes"] = true
F["Lago de Fogo"] = true
F["Laguna de Peixes-zebra Brilhantes"] = true
F["Lodo do Gourami-tigre"] = true
F["Mandarins Vermelhos amontoados"] = true
F["Monte de Camarão Mantídeo Emaranhado"] = true
F["Peixe-espinho Tocado pelo Sha"] = true
F["Piramboia de Jade Brilhante"] = true
F["Piscina de Sangue"] = true
F["Poça Brilhante"] = true
F["Poça de Gema de Garça"] = true
F["Salmão Imperial em Frenesi Alcoólico"] = true
------------------------------------------------------------------------
-- ruRU: Russian
------------------------------------------------------------------------
-- F["Black Barracuda School"] = true
-- F["Cursed Queenfish School"] = true
-- F["Fever of Stormrays"] = true
-- F["Highmountain Salmon School"] = true
-- F["Mossgill Perch School"] = true
-- F["Runescale Koi School"] = true
F["Блестящая нефритовая двоякодышащая рыба"] = true
F["Большая стая запутавшихся раков-богомолов"] = true
F["Большая стая мигрировавших рифовых осьминогов"] = true
F["Большой косяк блестящей нефритовой двоякодышащей рыбы"] = true
F["Большой косяк илистого тигрового гурами"] = true
F["Большой косяк испуганного веслоноса"] = true
F["Большой косяк пораженной ша иглоспинки"] = true
F["Большой косяк разъяренного хмелем императорского лосося"] = true
F["Большой косяк сверкающего бриллиантового данио"] = true
F["Большой косяк стайного краснобрюхого окуня"] = true
F["Журавлиная заводь"] = true
F["Илистый тигровый гурами"] = true
F["Косяк безротого скрытиуса"] = true
F["Косяк бешенки-сквернорота"] = true
F["Косяк большого шалфокуня"] = true
F["Косяк борейского медузника"] = true
F["Косяк бриллиантового данио"] = true
F["Косяк высокогорных гуппи"] = true
F["Косяк глубинного угря-мешкорота"] = true
F["Косяк глубоководного чуда-юда"] = true
F["Косяк глубоководного шалфокуня"] = true
F["Косяк горной форели"] = true
F["Косяк дракоперой рыбы-ангела"] = true
F["Косяк ершей"] = true
F["Косяк жирных морских скорпионов"] = true
F["Косяк загадочной рыбы"] = true
F["Косяк иглоспинки"] = true
F["Косяк илистого чернобрюха"] = true
F["Косяк ильной рыбы"] = true
F["Косяк императорского лосося"] = true
F["Косяк испуганноого веслоноса"] = true
F["Косяк клыкозубой сельди"] = true
F["Косяк королевского морского дьявола"] = true
F["Косяк красарангского веслоноса"] = true
F["Косяк краснобрюхой мандаринки"] = true
F["Косяк ледникового лосося"] = true
F["Косяк ледоспинки"] = true
F["Косяк лунной каракатицы"] = true
F["Косяк луфаря"] = true
F["Косяк масляного глубинного угря-мешкорота"] = true
F["Косяк масляного черноротика"] = true
F["Косяк морских скорпионов"] = true
F["Косяк морской рыбы"] = true
F["Косяк нефритовой двоякодышащей рыбы"] = true
F["Косяк огненного аммонита"] = true
F["Косяк огнеперого луциана"] = true
F["Косяк разной океанской рыбы"] = true
F["Косяк ракушечного подкаменщика"] = true
F["Косяк рифовых осьминогов"] = true
F["Косяк рыбы"] = true
F["Косяк сверкающего бриллиантового данио"] = true
F["Косяк слепоглазок-альбиносов"] = true
F["Косяк слепого озерного осетра"] = true
F["Косяк спороуса"] = true
F["Косяк тигровых гурами"] = true
F["Косяк толстопузика"] = true
F["Косяк хлыстохвоста Черноводья"] = true
F["Косяк шалфокуня"] = true
F["Лужа крови"] = true
F["Лужа огня"] = true
F["Обломки в воде"] = true
F["Обломки кораблекрушения Кровавого Паруса"] = true
F["Обломки кораблекрушения"] = true
F["Обломки парового насоса"] = true
F["Плавающие обломки"] = true
F["Плавающий мусор"] = true
F["Пораженная ша иглоспинка"] = true
F["Пруд свирепых пираний"] = true
F["Разбитая шхуна"] = true
F["Разъяренный хмелем императорский лосось"] = true
F["Сверкающая лужа"] = true
F["Смешанный косяк нагорья"] = true
F["Стайка каменного угря"] = true
F["Стайка медуз"] = true
F["Стайка саженного угря"] = true
F["Стайный краснобрюхий окунь"] = true
F["Стая гигантских раков-богомолов"] = true
F["Стая запутавшихся раков-богомолов"] = true
F["Стая мигрировавших рифовых осьминогов"] = true
F["Странный водоем"] = true
F["Чистая вода"] = true
------------------------------------------------------------------------
-- koKR: Korean
------------------------------------------------------------------------
-- F["Black Barracuda School"] = true
-- F["Cursed Queenfish School"] = true
-- F["Fever of Stormrays"] = true
-- F["Highmountain Salmon School"] = true
-- F["Mossgill Perch School"] = true
-- F["Runescale Koi School"] = true
-- F["Brew Frenzied Emperor Salmon"] = true
-- F["Crane Yolk Pool"] = true
-- F["Crowded Redbelly Mandarin"] = true
-- F["Felmouth Frenzy School"] = true
-- F["Glowing Jade Lungfish"] = true
-- F["Lagoon Pool"] = true
-- F["Large Pool of Brew Frenzied Emperor Salmon"] = true
-- F["Large Pool of Crowded Redbelly Mandarin"] = true
-- F["Large Pool of Glimmering Jewel Danio"] = true
-- F["Large Pool of Glowing Jade Lungfish"] = true
-- F["Large Pool of Sha-Touched Spinefish"] = true
-- F["Large Pool of Tiger Gourami Slush"] = true
-- F["Large Swarm of Migrated Reef Octopus"] = true
-- F["Large Swarm of Panicked Paddlefish"] = true
-- F["Large Tangled Mantis Shrimp Cluster"] = true
-- F["Mixed Ocean School"] = true
-- F["Oily Abyssal Gulper School"] = true
-- F["Oily Se Scorpion School"] = true
-- F["Pool of Blood"] = true
-- F["Sha-Touched Spinefish"] = true
-- F["Sparkling Pool"] = true
-- F["Strange Pool"] = true
-- F["Swarm of Migrated Reef Octopus"] = true
-- F["Swarm of Panicked Paddlefish"] = true
-- F["Tangled Mantis Shrimp Cluster"] = true
-- F["Tiger Gourami Slush"] = true
F["가시고기 떼"] = true
F["거대 사마귀 새우 떼"] = true
F["검은물 채찍꼬리 떼"] = true
F["검은배 미꾸라지 떼"] = true
F["검은색 물고기 떼"] = true
F["게르치 떼"] = true
F["고원 송사리 떼"] = true
F["고원의 물고기 떼"] = true
F["기름기 많은 아귀 떼"] = true
F["깊은 바다 뚱뚱보물고기 떼"] = true
F["깨끗한 물"] = true
F["난파선 파편"] = true
F["눈먼 철갑상어 떼"] = true
F["달빛 오징어 떼"] = true
F["대형 총명어 떼"] = true
F["돌비늘뱀장어 떼"] = true
F["돌연변이 물고기 떼"] = true
F["무턱 모래무지 떼"] = true
F["물에 젖은 잔해"] = true
F["미꾸라지 떼"] = true
F["바다 전갈 떼"] = true
F["백색 동굴어 떼"] = true
F["범선 잔해"] = true
F["보석 열대어 떼"] = true
F["북풍 해파리 떼"] = true
F["불지느러미퉁돔 떼"] = true
F["불타는 웅덩이"] = true
F["붉은배 쏘가리 떼"] = true
F["붉은해적단 잔해"] = true
F["비취 폐어 떼"] = true
F["빙하연어 떼"] = true
F["산악 송어 떼"] = true
F["송곳니 청어 떼"] = true
F["심연 뱀장어 떼"] = true
F["심연 풍선장어 떼"] = true
F["심해 총명어 떼"] = true
F["암초문어 떼"] = true
F["야만적인 피라냐떼"] = true
F["용지느러미 천사돔 떼"] = true
F["유리지느러미 송사리 떼"] = true
F["조개등 둑중개 떼"] = true
F["증기 양수기 부품"] = true
F["총명어 떼"] = true
F["크라사랑 주걱철갑상어 떼"] = true
F["통통 망둑어 떼"] = true
F["포자물고기 떼"] = true
F["표류하는 잔해"] = true
F["표류하는 파편"] = true
F["해파리 떼"] = true
F["호랑이 구라미 떼"] = true
F["화염 암모나이트 떼"] = true
F["황금 화살고기 떼"] = true
F["황제 쥐가오리 떼"] = true
F["황제연어 떼"] = true
------------------------------------------------------------------------
-- zhCN: Simplified Chinese
------------------------------------------------------------------------
-- F["Black Barracuda School"] = true
-- F["Cursed Queenfish School"] = true
-- F["Fever of Stormrays"] = true
-- F["Highmountain Salmon School"] = true
-- F["Mossgill Perch School"] = true
-- F["Runescale Koi School"] = true
-- F["Lagoon Pool"] = true
-- F["Large Pool of Brew Frenzied Emperor Salmon"] = true
-- F["Large Pool of Crowded Redbelly Mandarin"] = true
-- F["Large Pool of Tiger Gourami Slush"] = true
-- F["Oily Abyssal Gulper School"] = true
-- F["Oily Sea Scorpion School"] = true
-- F["Pool of Blood"] = true
-- F["Savage Piranha Pool"] = true
-- F["Sea Scorpion School"] = true
-- F["Sparkling Pool"] = true
-- F["Swarm of Migrated Reef Octopus"] = true
-- F["Tiger Gourami Slush"] = true
F["一大群微光珍宝斑马鱼"] = true
F["一大群恐慌的白鲟鱼"] = true
F["一大群染煞刺皮鱼"] = true
F["一大群混乱的巨型螳螂虾群"] = true
F["一大群迁徙的八爪鱼"] = true
F["一大群闪光翠绿肺鱼"] = true
F["一滩蛋黄"] = true
F["一群恐慌的白鲟鱼"] = true
F["八爪鱼群"] = true
F["冰河鲑鱼群"] = true
F["利齿青鱼群"] = true
F["刺皮鱼群"] = true
F["北风水母群"] = true
F["卡桑琅白鲟鱼群"] = true
F["发酒疯的帝王鲑鱼"] = true
F["变异鱼群"] = true
F["塘鲈鱼群"] = true
F["大型鼠尾鱼群"] = true
F["奇怪的水池"] = true
F["孢子鱼群"] = true
F["巨型螳螂虾群"] = true
F["帆船残骸"] = true
F["帝王鲑鱼群"] = true
F["帝王鳐群"] = true
F["微光珍宝斑马鱼"] = true
F["拥挤的红腹鳜鱼群"] = true
F["无颚潜鱼群"] = true
F["晶鳞鱼群"] = true
F["月光墨鱼群"] = true
F["染煞刺皮鱼群"] = true
F["水母群"] = true
F["泥鱼群"] = true
F["浸水的残骸"] = true
F["深水鳗鱼群"] = true
F["深海巨腹鱼群"] = true
F["深海鼠尾鱼群"] = true
F["深渊大嘴鳗鱼群"] = true
F["混乱的巨型螳螂虾群"] = true
F["混合海鱼群"] = true
F["漂浮的残骸"] = true
F["漂浮的碎片"] = true
F["火池"] = true
F["火鳞鳝鱼群"] = true
F["熔火鱿鱼群"] = true
F["珍宝斑马鱼群"] = true
F["白色洞穴鱼群"] = true
F["盲眼湖鲟鱼群"] = true
F["石鳞鳗群"] = true
F["红腹鳜鱼"] = true
F["纯净的水"] = true
F["翠绿肺鱼群"] = true
F["船只残骸"] = true
F["蒸汽泵废料"] = true
F["蓝鱼群"] = true
F["虎皮丝足鱼群"] = true
F["蚌背鱼群"] = true
F["血帆船只残骸"] = true
F["金镖鱼群"] = true
F["闪光翠绿肺鱼"] = true
F["高地孔雀鱼群"] = true
F["高地杂鱼群"] = true
F["高山鲑鱼群"] = true
F["魔口狂鱼群"] = true
F["魔尾鱼群"] = true
F["黑口鱼群"] = true
F["黑水鞭尾鱼群"] = true
F["黑腹泥鱼群"] = true
F["鼠尾鱼群"] = true
F["龙鳞天使鱼群"] = true
------------------------------------------------------------------------
-- zhTW: Traditional Chinese
------------------------------------------------------------------------
-- F["Black Barracuda School"] = true
-- F["Cursed Queenfish School"] = true
-- F["Fever of Stormrays"] = true
-- F["Highmountain Salmon School"] = true
-- F["Mossgill Perch School"] = true
-- F["Runescale Koi School"] = true
-- F["Brackish Mixed School"] = true
-- F["Brew Frenzied Emperor Salmon"] = true
-- F["Crane Yolk Pool"] = true
-- F["Crowded Redbelly Mandarin"] = true
-- F["Felmouth Frenzy School"] = true
-- F["Glimmering Jewel Danio Pool"] = true
-- F["Glowing Jade Lungfish"] = true
-- F["Jawless Skulker School"] = true
-- F["Lagoon Pool"] = true
-- F["Large Pool of Brew Frenzied Emperor Salmon"] = true
-- F["Large Pool of Crowded Redbelly Mandarin"] = true
-- F["Large Pool of Glimering Jewel Danio"] = true
-- F["Large Pool of Glowing Jade Lungfish"] = true
-- F["Large Pool of Sha-Touched Spinefish"] = true
-- F["Large Pool of Tiger Gourami Slush"] = true
-- F["Large Swarm of Migrated Reef Octopus"] = true
-- F["Large Swarm of Panicked Paddlefish"] = true
-- F["Large Tangled Mantis Shrimp Cluster"] = true
-- F["Mixed Ocean School"] = true
-- F["Oily Abyssal Gulper School"] = true
-- F["Oily Sea Scorpion School"] = true
-- F["Pool of Blood"] = true
-- F["Savage Piranha Pool"] = true
-- F["Sha-Touched Spinefish"] = true
-- F["Swarm of Migrated Reef Octopus"] = true
-- F["Swarm of Panicked Paddlefish"] = true
-- F["Tiger Gourami Slush"] = true
F["冰川鮭魚群"] = true
F["北風水母群"] = true
F["喀撒朗匙吻鱘魚群"] = true
F["大型鼠尾魚群"] = true
F["奇怪的水池"] = true
F["孢子魚群"] = true
F["尖齒鯡魚群"] = true
F["山脈鱒魚群"] = true
F["巨型螳螂蝦群"] = true
F["帝王韌皮魟魚群"] = true
F["帝王鮭魚群"] = true
F["暗礁章魚群"] = true
F["月色墨魚群"] = true
F["棘魚群"] = true
F["沉船殘骸"] = true
F["泥鰍群"] = true
F["海蠍群"] = true
F["浸水的殘骸"] = true
F["淡水魚群"] = true
F["深海大肚魚群"] = true
F["深海鼠尾魚群"] = true
F["深淵大嘴鰻群"] = true
F["漂浮殘骸"] = true
F["漂浮的殘骸"] = true
F["漂浮的碎片"] = true
F["澗鰻群"] = true
F["火池"] = true
F["火焰菊石群"] = true
F["火鰭鯛魚群"] = true
F["玻鰭小鯉魚群"] = true
F["珠寶斑馬魚群"] = true
F["白化穴魚群"] = true
F["盲湖鱘魚群"] = true
F["石鱗鰻魚群"] = true
F["紅肚桂花魚群"] = true
F["純水"] = true
F["翠玉龍魚群"] = true
F["胖睡魚魚群"] = true
F["蒸汽幫浦漂浮殘骸"] = true
F["蕁麻魚群"] = true
F["藍魚群"] = true
F["虎斑絲足魚群"] = true
F["蚌脊魚群"] = true
F["血帆殘骸"] = true
F["變異魚群"] = true
F["高地孔雀魚群"] = true
F["高地綜合魚群"] = true
F["魔尾魚群"] = true
F["黑口魚群"] = true
F["黑水鞭尾魚群"] = true
F["黑肚泥鰍群"] = true
F["鼠尾魚群"] = true
F["龍鱗天使魚群"] = true
