--[[--------------------------------------------------------------------
	GoFish
	Click-cast fishing and enhanced fishing sounds.
	Copyright (c) 2013-2015 Phanx <addons@phanx.net>. All rights reserved.
	http://www.wowinterface.com/downloads/info22270-GoFish.html
	http://www.curse.com/addons/wow/gofish
	https://github.com/Phanx/GoFish
----------------------------------------------------------------------]]
local L, _, ns = {}, ...
ns.L = L

-- THE REST OF THIS FILE IS AUTOMATICALLY GENERATED. SEE:
-- http://wow.curseforge.com/addons/gofish/localization/

------------------------------------------------------------------------
-- English
------------------------------------------------------------------------

L.ActivateOnEquip = "Activate when equipping a fishing pole"
L.ActivateOnEquip_Tooltip = "Automatically turn on fishing mode while you have a fishing pole equipped."
L.ActivateOnMouseover = "Activate when mousing over a fish pool"
L.ActivateOnMouseover_Tooltip = "Automatically turn on fishing mode when you mouse over a fish pool. When activated this way, fishing mode is disabled after 10 seconds if you don't cast."
L.AmbienceVolume_Tooltip = "Adjusts the ambient sound volume while fishing."
L.EnhanceSounds = "Enhance sound effects while fishing"
L.EnhanceSounds_Tooltip = "To better hear the fishing bobber splash, turn Sounds up, and Music and Ambience down. Your normal sound levels are restored after fishing."
L.FishingModeOff = "Quick fishing {OFF}"
L.FishingModeOn = "Quick fishing {ON}"
L.MasterVolume_Tooltip = "Adjusts the master volume while fishing."
L.MusicVolume_Tooltip = "Adjusts the music volume while fishing."
L.SFXVolume_Tooltip = "Adjusts the sound effect volume while fishing."
L.ToggleFishingMode = "Toggle quick fishing"

local CURRENT_LOCALE = GetLocale()
if CURRENT_LOCALE == "enUS" then return end

------------------------------------------------------------------------
-- German
------------------------------------------------------------------------

if CURRENT_LOCALE == "deDE" then

L.ActivateOnEquip = "Aktivieren beim Ausrüsten einer Angel"
L.ActivateOnEquip_Tooltip = "Automatisch Schnellangeln aktivieren wenn du eine Angel trägst."
L.ActivateOnMouseover = "Bei Mouseover von Schwärmen aktivieren"
L.ActivateOnMouseover_Tooltip = "Automatisch Schnellangeln aktivieren wenn du einen Schwarm hoverst. Solltest du nicht innerhalb 10 Sekunden angeln, deaktiviert der Modus automatisch."
L.AmbienceVolume_Tooltip = "Passt Umgebungsgeräusche an, während du angelst."
L.EnhanceSounds = "Soundeffekte verstärken wenn du angelst"
L.EnhanceSounds_Tooltip = "Um den Köder besser zu hören, erhöht die Lautstärke und reduziert Musik und Umgebungsgeräusche. Deine normalen Einstellungen werden nach dem Angeln wiederhergestellt."
L.FishingModeOff = "Schnellangeln {AUS}"
L.FishingModeOn = "Schnellangeln {AN}"
L.MasterVolume_Tooltip = "Gesamtlautstärke beim Angeln anpassen"
L.MusicVolume_Tooltip = "Passt die Musiklautstärke beim Angeln an."
L.SFXVolume_Tooltip = "Passt die Effektlautstärke beim Angeln an."
L.ToggleFishingMode = "Schnellangeln umschalten"

return end

------------------------------------------------------------------------
-- Spanish
------------------------------------------------------------------------

if CURRENT_LOCALE == "esES" then

L.ActivateOnEquip = "Activa al equipar una caña de pescar"
L.ActivateOnEquip_Tooltip = "Activar automáticamente el modo de pesca mientras que tienes equipada una caña de pescar."
L.ActivateOnMouseover = "Activa al pasar el ratón sobre banco"
L.ActivateOnMouseover_Tooltip = "Activar automáticamente el modo de pesca al pasar el ratón sobre un banco de peces. Cuando se activa este manera, el modo de pesca se desactiva si no pescas durante 10 segundos."
L.AmbienceVolume_Tooltip = "Ajusta el volumen del sonido ambiental mientras que estás pescando."
L.EnhanceSounds = "Mejora los efectos de sonido"
L.EnhanceSounds_Tooltip = "Para escuchar mejor el sonido del cebo, suba los efectos de sonido, y baja la música y el sonido ambiental. Los niveles originales de sonido se restauran después de la pesca."
L.FishingModeOff = "Pesca rápida {activó}"
L.FishingModeOn = "Pesca rápida {desactivó}"
L.MasterVolume_Tooltip = "Ajusta el volumen general del sonido mientras que estás pescando."
L.MusicVolume_Tooltip = "Ajusta el volumen de la música mientras que estás pescando."
L.SFXVolume_Tooltip = "Ajusta el volumen de los efectos de sonido mientras que estás pescando."
L.ToggleFishingMode = "Activar/desactivar pesca rápida"

return end

------------------------------------------------------------------------
-- Latin American Spanish
------------------------------------------------------------------------

if CURRENT_LOCALE == "esMX" then

L.ActivateOnEquip = "Activa al equipar una caña de pescar"
L.ActivateOnEquip_Tooltip = "Activar automáticamente el modo de pesca mientras que tienes equipada una caña de pescar."
L.ActivateOnMouseover = "Activa al pasar el ratón sobre banco"
L.ActivateOnMouseover_Tooltip = "Activar automáticamente el modo de pesca al pasar el ratón sobre un banco de peces. Cuando se activa este manera, el modo de pesca se desactiva si no pescas durante 10 segundos."
L.AmbienceVolume_Tooltip = "Ajusta el volumen del sonido ambiental mientras que estás pescando."
L.EnhanceSounds = "Mejora los efectos de sonido"
L.EnhanceSounds_Tooltip = "Para escuchar mejor el sonido del cebo, suba los efectos de sonido, y baja la música y el sonido ambiental. Los niveles originales de sonido se restauran después de la pesca."
L.FishingModeOff = "Pesca rápida {activó}"
L.FishingModeOn = "Pesca rápida {desactivó}"
L.MasterVolume_Tooltip = "Ajusta el volumen general del sonido mientras que estás pescando."
L.MusicVolume_Tooltip = "Ajusta el volumen de la música mientras que estás pescando."
L.SFXVolume_Tooltip = "Ajusta el volumen de los efectos de sonido mientras que estás pescando."
L.ToggleFishingMode = "Activar/desactivar pesca rápida"

return end

------------------------------------------------------------------------
-- French
------------------------------------------------------------------------

if CURRENT_LOCALE == "frFR" then

return end

------------------------------------------------------------------------
-- Italian
------------------------------------------------------------------------

if CURRENT_LOCALE == "itIT" then

return end

------------------------------------------------------------------------
-- Brazilian Portuguese
------------------------------------------------------------------------

if CURRENT_LOCALE == "ptBR" then

L.FishingModeOff = "Pesca rápida {ativou}"
L.FishingModeOn = "Pesca rápida {desativou}"
L.ToggleFishingMode = "Ativar/desativar pesca rápida"

return end

------------------------------------------------------------------------
-- Russian
------------------------------------------------------------------------

if CURRENT_LOCALE == "ruRU" then

return end

------------------------------------------------------------------------
-- Korean
------------------------------------------------------------------------

if CURRENT_LOCALE == "koKR" then

return end

------------------------------------------------------------------------
-- Simplified Chinese
------------------------------------------------------------------------

if CURRENT_LOCALE == "zhCN" then

return end

------------------------------------------------------------------------
-- Traditional Chinese
------------------------------------------------------------------------

if CURRENT_LOCALE == "zhTW" then

L.ActivateOnEquip = "當裝備一個釣魚竿時啟動"
L.ActivateOnEquip_Tooltip = "當你有裝備一個釣魚竿時，自動開啟釣魚模式。"
L.ActivateOnMouseover = "當滑鼠指向一個魚池時啟動"
L.ActivateOnMouseover_Tooltip = "當你滑鼠指向一個魚池自動開啟釣魚模式，當以此途徑啟動時，如果10秒沒動作之後釣魚模式將關閉。"
L.AmbienceVolume_Tooltip = "當釣魚時調整環境的音量。"
L.EnhanceSounds = "當釣魚時提高音效"
L.EnhanceSounds_Tooltip = "為更好的聽到釣魚浮標的飛濺聲，提高音效的音量，並同時降低音樂與環境的音量。當釣魚結束後音效會恢復原來的水平。"
L.FishingModeOff = "快速釣魚{OFF}"
L.FishingModeOn = "快速釣魚{ON}"
L.MasterVolume_Tooltip = "當釣魚時調整主音量。"
L.MusicVolume_Tooltip = "當釣魚時調整音樂的音量。"
L.SFXVolume_Tooltip = "當釣魚時調整音效的音量。"
L.ToggleFishingMode = "開關快速釣魚"

return end
